package uk.cybertecpro.cyberlearningos

data class StepLesson(
    val technique: String,
    val explanation: String,
    val avoid: String,
    val walkthrough: List<String>,
    val diagram: List<String>,
    val guidedPractice: String,
    val transcriptAnchor: String,
)

/**
 * Teaching content derived from Dr Justin Sung's 14-step flowchart video transcript.
 * This sits beside the evidence contract: first teach the method, then ask the learner to use it.
 */
object TeachingContent {
    val lessons = listOf(
        StepLesson(
            "Outcome scoreboard",
            "Judge a learning method by the depth of knowledge you can use and how well it survives over time. Fast coverage can create fragile familiarity and later force you to relearn everything.",
            "Do not keep or reject a technique merely because it makes today's study session faster or slower.",
            listOf(
                "Name the real performance you need: explain, investigate, decide, build, or brief.",
                "Choose an immediate depth check that requires use, not recognition.",
                "Choose a delayed retention check and a transfer check using a different case.",
                "Record time spent only as a cost beside these outcomes—not as the definition of success.",
            ),
            listOf("METHOD", "DEEP USE", "DELAY", "TRANSFER", "OUTCOME"),
            "After studying an authentication flow, close the source, reconstruct it, diagnose a broken login from logs, and repeat with a different identity case several days later.",
            "Video 1:04–2:24 — replace speed as the primary metric with depth and retention.",
        ),
        StepLesson(
            "Purpose-and-plan canvas",
            "The brain needs a goal and a frame of context. A curriculum supplies objectives and past performance formats; unstructured professional learning requires you to create them yourself.",
            "Do not begin with a vague instruction such as ‘learn cloud security’ or let the source decide what success means.",
            listOf(
                "Write why this matters to a role, problem, decision, or project.",
                "Inspect formal objectives, structure, and sample assessments when they exist.",
                "For informal learning, write your own two to four learning objectives.",
                "Describe exactly how you will apply and perform with the knowledge.",
                "Remove content that cannot be traced to the purpose.",
            ),
            listOf("PURPOSE", "OBJECTIVES", "PERFORMANCE", "EVIDENCE"),
            "Purpose: investigate token abuse. Objectives: explain token lifetime, identify relevant logs, distinguish theft from replay, and recommend containment.",
            "Video 2:27–3:37 — create a clear purpose and plan before diving into content.",
        ),
        StepLesson(
            "Time-block design",
            "Available time changes which learning strategy is realistic. Long sessions support integration and performance; short blocks suit priming, retrieval, or one focused relationship.",
            "Do not rely on finding spare time, and do not force a long-session method into a ten-minute gap.",
            listOf(
                "Put actual learning blocks in the calendar before the week fills up.",
                "Label each block as prime, intensive learning, practice, retrieval, or review.",
                "Match the task to the block length instead of only shrinking the same task.",
                "Reserve a smaller priming block before each intensive block.",
                "Name one artifact the block must produce.",
            ),
            listOf("CALENDAR", "PRIME", "LEARN", "PERFORM", "REVIEW"),
            "Use a 10-minute commute for a SIEM-topic preview, a 60-minute block for log relationships, and a 30-minute later block for an unaided hunt.",
            "Video 3:38–4:17 — schedule first because available time determines method choice.",
        ),
        StepLesson(
            "Priming preview",
            "Priming tells the brain what is coming before intensive learning. Like being warned where a ball will be thrown, it creates readiness, reduces overwhelm, and helps new information form memory.",
            "Do not turn priming into a full study session or wait until the difficult material has already overloaded you.",
            listOf(
                "Place a short preview minutes, days, or up to a week before intensive study.",
                "Scan headings, objectives, diagrams, summaries, vocabulary, and the final task.",
                "Mark unfamiliar terms and prerequisites without solving them yet.",
                "Predict the major parts and how they may connect.",
                "Stop while the preview is still light and incomplete.",
            ),
            listOf("PREVIEW", "LANDMARKS", "QUESTIONS", "INTENSIVE STUDY"),
            "Before a malware-analysis lab, preview the process tree, persistence points, evidence types, tools, and expected report without investigating the sample.",
            "Video 4:18–5:27 — plan a smaller priming block before dedicated learning.",
        ),
        StepLesson(
            "Gist map",
            "Priming should create an overall idea and a few memory landmarks. Details become meaningful when they can attach to a rough whole.",
            "Do not pre-study every detail. If priming an hour of material takes much longer than five to ten minutes, you are probably studying rather than priming.",
            listOf(
                "Set a five-to-ten-minute timer for roughly one hour of upcoming learning.",
                "Skim for the central problem, actors, flow, boundaries, and outcome.",
                "Write a one-sentence provisional gist in plain language.",
                "Draw only four to six anchor concepts and tentative links.",
                "Mark uncertainty with question marks and stop when the timer ends.",
            ),
            listOf("WHO/WHAT", "FLOW", "BOUNDARY", "EVIDENCE", "PURPOSE"),
            "Gist: ‘EDR continuously collects endpoint behaviour so analysts can connect activity into detections, investigations, and response—not merely block known malware.’",
            "Video 5:28–6:55 — focus priming on the gist; five to ten minutes per hour is the warning boundary.",
        ),
        StepLesson(
            "Distraction sheet",
            "A focused environment is tested through evidence, not intuition. A distraction sheet reveals what repeatedly steals attention so the next session can be designed around the real problem.",
            "Do not call an environment focused merely because it feels quiet, and do not chase every thought that appears.",
            listOf(
                "Put a blank distraction sheet beside the active learning surface.",
                "Each time attention moves away, make one quick tally and name the trigger.",
                "Return immediately; do not solve the distraction during the session.",
                "Afterward, group triggers as device, environment, uncertainty, fatigue, or interruption.",
                "Remove or contain the repeated triggers before the next block.",
            ),
            listOf("FOCUS", "DISTRACTION", "TALLY", "REMOVE CAUSE", "RETRY"),
            "During PCAP analysis, tally chat notifications, unrelated CVE searches, and uncertainty about DNS. Silence chat, park CVEs, and make DNS the next prerequisite.",
            "Video 7:14–7:51 — use a distraction sheet; ideally it remains blank.",
        ),
        StepLesson(
            "Schema-building questions",
            "Memory is built as a connected schema. Deliberately comparing, judging importance, and relating new information triggers deeper processing than trying to remember or merely understand sentences.",
            "Do not make memorisation your first resort. Flashcards are for genuinely arbitrary residue after connection attempts, not the main learning system.",
            listOf(
                "For every major idea ask: what is it similar to and different from?",
                "Ask what it depends on, what it changes, and what breaks when it fails.",
                "Judge its importance relative to your purpose rather than treating all facts equally.",
                "Connect it to prior knowledge, telemetry, controls, risk, and decisions.",
                "Only place an unconnectable fact into spaced retrieval after making a serious connection attempt.",
            ),
            listOf("NEW IDEA", "COMPARE", "JUDGE", "CONNECT", "SCHEMA"),
            "Compare EDR and NDR by visibility, blind spots, evidence, evasion, operational cost, and the incident decisions each can support.",
            "Video 7:53–10:52 — trying to remember is a poor way to remember; prioritise comparisons and relationships.",
        ),
        StepLesson(
            "Relational note map",
            "Notes for learning should expose how ideas relate. Non-linear maps show your thinking, while linear notes are mainly justified when deliberately creating a future reference resource.",
            "Do not transcribe the source line by line or decorate a list with arrows after the relationships were never reasoned through.",
            listOf(
                "Place the central question or capability—not the source title—in the centre.",
                "Add a small number of concepts as nodes, using your own short labels.",
                "Connect nodes with labelled relationships such as causes, requires, reveals, contradicts, or mitigates.",
                "Add contrasts, failure modes, and cross-links between branches.",
                "Attach evidence or source references to claims; revise the map after testing it on a new question.",
            ),
            listOf("QUESTION", "MECHANISM", "ATTACK", "TELEMETRY", "DECISION"),
            "Centre ‘How is token replay detected?’ Link token lifecycle → replay opportunity → identity/network evidence → correlation → containment, with ‘fails when’ links for visibility gaps.",
            "Video 10:54–12:24 — use non-linear notes to see connections; linear notes remain a reference exception.",
        ),
        StepLesson(
            "Relevance-led route",
            "The best learning order is the order your current knowledge can make meaningful. When a concept is too difficult, find an easier relevant idea that supplies missing context, then return.",
            "Do not blindly follow chapter order, repeatedly force an unintelligible point, or memorise it solely to escape difficulty.",
            listOf(
                "Start with the goal, incident, or concept currently easiest to make meaningful.",
                "When blocked, state which context appears to be missing.",
                "Move to an easier related mechanism, example, or prerequisite.",
                "Add the new relationship to your map.",
                "Return to the original hard point and test whether it now makes sense.",
            ),
            listOf("HARD POINT", "MISSING CONTEXT", "EASIER NODE", "CONNECT", "RETURN"),
            "If Kerberos delegation is opaque, step back to tickets, service principals, and trust boundaries; map them, then return to constrained delegation abuse.",
            "Video 12:25–13:45 — individualise order by relevance and use easier context to unlock hard points.",
        ),
        StepLesson(
            "Confusion compass",
            "Confusion is evidence that your brain has found a gap while comparing or judging ideas. Turn the vague feeling into a question so attention has a diagnostic target.",
            "Do not remove discomfort by oversimplifying, ignoring the question, or treating absence of confusion as proof of mastery.",
            listOf(
                "Pause and write: ‘I am confused because…’",
                "Name the two claims, observations, or relationships that do not fit together.",
                "Convert the conflict into one precise question.",
                "Write your current hypothesis and what evidence would support or refute it.",
                "Investigate, update the map, and preserve what changed in your thinking.",
            ),
            listOf("CONFUSION", "CONFLICT", "QUESTION", "HYPOTHESIS", "EVIDENCE"),
            "‘MFA succeeded, yet the alert says impossible travel.’ Question whether the event represents new authentication or reuse of an already issued session token.",
            "Video 15:25–19:15 — explore confusion and convert it into focused questions.",
        ),
        StepLesson(
            "Challenge matcher",
            "Testing must resemble the required performance across three dimensions: style, level, and cue. Fact recall cannot validate complex decisions, and prompted recall cannot validate unaided performance.",
            "Do not substitute definitions or multiple-choice recognition for an investigation, discussion, presentation, or decision you must perform.",
            listOf(
                "Name the target challenge style: explain, query, investigate, build, decide, or present.",
                "Match the cognitive level: recall, application, complex problem, trade-off, or defence.",
                "Match the cue: supplied question, partial evidence, discussion prompts, or no cue.",
                "Create a practice task in the same ballpark—not necessarily an exact copy.",
                "Judge the artifact and reasoning against the target performance.",
            ),
            listOf("STYLE", "LEVEL", "CUE", "SIMULATION", "PERFORMANCE"),
            "For a SOC interview, investigate unfamiliar logs without a query hint, explain competing hypotheses, choose an action, and brief the interviewer—not just define beaconing.",
            "Video 19:16–21:01 — match challenge style, level, and cue to the real performance.",
        ),
        StepLesson(
            "Attempt-feedback boundary",
            "Generating an answer before feedback exercises recall and primes the brain to learn from correction. Looking first tests recognition; hints during an attempt can inflate confidence unless the real task also supplies them.",
            "Do not reveal the answer before trying, overwrite the first attempt, or let AI quietly complete the reasoning while calling it unaided.",
            listOf(
                "Hide solutions, notes, AI, hints, and feedback.",
                "Make a complete, time-bounded attempt—even when uncertain or probably wrong.",
                "Freeze the original answer, reasoning path, decision, and confidence.",
                "Only then open feedback or AI critique.",
                "Compare line by line: correct, missing, wrong, weakly supported, and why.",
            ),
            listOf("CLOSED BOOK", "GENERATE", "FREEZE", "FEEDBACK", "CORRECT"),
            "Write a Sigma rule and predict matching events before viewing a reference or AI suggestion; retain both versions and explain each material change.",
            "Video 21:02–23:22 — generate a full response first; feedback afterward is usually ideal.",
        ),
        StepLesson(
            "Forgetting calibration",
            "Testing frequency matters less when knowledge is deeply connected. Test after enough forgetting to make retrieval effortful but before relearning dominates—approximately 20–30% forgotten.",
            "Do not use a rigid universal schedule, test immediately while everything is active, or wait until the topic feels completely new.",
            listOf(
                "After initial learning, predict a first review window—often one week to one month for well-connected knowledge.",
                "Attempt retrieval without cues and estimate what was missing.",
                "If almost nothing was forgotten, lengthen the next interval.",
                "If reconstructing required major relearning, shorten it.",
                "Use the observed forgetting level, not a streak, to choose the next review.",
            ),
            listOf("LEARN", "FORGET SOME", "RETRIEVE", "CALIBRATE", "NEXT INTERVAL"),
            "Reconstruct an incident-response decision tree after two weeks. If one branch is weak but the model survives, correct it and widen the interval; if the model collapses, review sooner.",
            "Video 23:23–24:58 — aim for roughly 20–30% forgetting; often one week to one month when earlier steps are strong.",
        ),
        StepLesson(
            "Pressure rehearsal",
            "Matching every encoding condition is impractical and usually low value. Match the conditions that materially change workplace performance: intensity, nervousness, scrutiny, and time.",
            "Do not waste effort copying room, food, caffeine, or every physical detail while ignoring strict timing, ambiguity, or being questioned.",
            listOf(
                "List the meaningful constraints of the real task: time, scrutiny, uncertainty, interruptions, and available cues.",
                "Choose the two or three most performance-relevant conditions.",
                "Rehearse with a timer and realistic information limits.",
                "Add questioning or an audience when the target involves defence or presentation.",
                "Debrief whether the method and judgement survived pressure—not whether the room looked similar.",
            ),
            listOf("REAL TASK", "TIME", "SCRUTINY", "UNCERTAINTY", "REHEARSE"),
            "Triage partial telemetry in 30 minutes, then defend confidence and containment to a skeptical incident lead who introduces one conflicting fact.",
            "Video 24:59–26:37 — reproduce intensity, nervousness, and time; exact environmental matching is not practical.",
        ),
    )

    fun forStep(stepNumber: Int): StepLesson = lessons[(stepNumber - 1).coerceIn(lessons.indices)]
}
