namespace CyberLearningOS.Windows;

public sealed record LearningStepGuide(
    int Number,
    string Phase,
    string Title,
    string What,
    string Why,
    string How,
    string CyberExample,
    string EvidencePrompt,
    string DoneWhen);

public static class LearningGuide
{
    public const string SourceUrl = "https://youtu.be/CQQTwvDb5xg";

    public static IReadOnlyList<LearningStepGuide> Steps { get; } =
    [
        Step(1, "Orient", "Measure outcomes, not speed",
            "Choose depth, delayed retention, and transfer as the scoreboard for whether learning worked.",
            "Fast coverage can create fragile familiarity and expensive relearning.",
            "1. Name the real performance: explain, investigate, decide, build, or brief.\n2. Choose an immediate depth check requiring use, not recognition.\n3. Choose delayed retention and different-case transfer checks.\n4. Record time only as a cost, not as success.",
            "After learning Kerberos, reconstruct the flow, diagnose a failure from logs, and repeat later with a different case.",
            "Record an immediate depth check, delayed retention check, transfer check, and time cost.",
            "The scoreboard measures performance now, after delay, and in a new case—not speed."),
        Step(2, "Orient", "Set a clear purpose and plan",
            "Connect the topic to a real problem, role, decision, or capability gap.",
            "Purpose directs attention and makes knowledge easier to retrieve in context.",
            "1. Complete 'I am learning this because...'.\n2. Write 2-4 questions the session must answer.\n3. State the cost of the gap.",
            "Learn OAuth attack paths to assess token abuse and ask better identity-incident questions.",
            "Record your purpose, 2-4 questions, and consequence of the gap.",
            "Every activity traces to the purpose or a question."),
        Step(3, "Orient", "Build an actual schedule",
            "Turn study time into a bounded mission with named outputs.",
            "A mission prevents reading from consuming application and retrieval time.",
            "1. Choose a session length.\n2. Allocate prime, acquire, connect, apply, retrieve, and communicate time.\n3. Name each output.",
            "For 120 minutes: 10 prime, 35 acquire, 25 connect, 25 apply, 15 retrieve, 10 brief.",
            "Write the timed mission and output for each block.",
            "Unaided performance and communication have protected time."),
        Step(4, "Prime", "Plan for priming",
            "Preview structure and vocabulary before learning details.",
            "Priming creates mental hooks and exposes missing prerequisites.",
            "1. Scan headings, diagrams, objectives, summaries, and terms.\n2. Mark prerequisites.\n3. Predict a rough topic map.",
            "Before cloud IAM, scan identity flows, trust boundaries, policy types, logs, and terms.",
            "Record expected structure, important terms, and prerequisites.",
            "You can describe the territory and its unknowns."),
        Step(5, "Prime", "Prime for the gist",
            "Form a provisional answer to what the topic is fundamentally about.",
            "A rough whole gives later details somewhere meaningful to attach.",
            "1. Write a 5-10 minute plain-language summary.\n2. Sketch a concept map.\n3. Mark uncertain links.",
            "EDR is continuous endpoint evidence plus analytics for detection, investigation, and response - not just antivirus.",
            "Write the gist and rough relationship map.",
            "A newcomer can follow it and uncertainties are visible."),
        Step(6, "Build & Connect", "Create a focused environment",
            "Use a distraction sheet to observe and remove the real triggers that break concentration.",
            "Focus is demonstrated through attention evidence, not assumed from intuition.",
            "1. Put a blank distraction sheet beside the task.\n2. Tally and name every trigger, then return.\n3. Group triggers after the session.\n4. Remove recurring causes before the next block.",
            "For packet analysis, keep only the PCAP, protocol reference, and active question visible.",
            "Record the distraction tally, trigger categories, and next-session environment change.",
            "A real session converted recurring distractions into specific controls."),
        Step(7, "Build & Connect", "Make connections the priority",
            "Learn dependencies, contrasts, failure modes, telemetry, and consequences.",
            "Senior judgement comes from relationships, not isolated definitions.",
            "1. Ask what, why, dependencies, similarities, differences, and failures.\n2. Identify telemetry and investigation paths.\n3. Connect mechanism to risk.",
            "Relate PowerShell policy to process creation, script-block logging, AMSI, bypasses, and detection limits.",
            "Record three relationships, one failure mode, and its telemetry.",
            "You can explain how one change affects evidence, control, and risk."),
        Step(8, "Build & Connect", "Take relational notes",
            "Capture a reasoning model rather than a transcript.",
            "Relational notes support investigation and transfer; copied prose mainly supports recognition.",
            "1. Put the central question—not the source title—in the centre.\n2. Add concepts as short nodes in your own words.\n3. Label links: causes, requires, reveals, contradicts, or mitigates.\n4. Add contrasts, failures, and cross-links.\n5. Attach evidence and revise after a new question.",
            "Map an exposed service through exploitation, network evidence, detection, containment, and impact.",
            "Create a relationship chain or concept map with evidence links.",
            "The notes answer new questions without copying source order."),
        Step(9, "Build & Connect", "Individualise the learning order",
            "Follow the order that resolves the problem, even when it differs from a course sequence.",
            "Problem-led order exposes prerequisites when they become meaningful.",
            "1. Start from the incident or capability.\n2. Trace backward to mechanisms and forward to decisions.\n3. Use source order only when it is the clearest dependency path.",
            "A suspicious PowerShell event can lead through processes, Sysmon, AMSI, ATT&CK, detection, and hunting.",
            "Record your chosen route, why it fits, and prerequisites found.",
            "Every detour closes a named dependency."),
        Step(10, "Build & Connect", "Use confusion as a compass",
            "Convert vague confusion into a precise missing relationship and testable hypothesis.",
            "Specific confusion creates a diagnostic path.",
            "1. Record expectation and observation.\n2. Name the missing link or assumption.\n3. State a hypothesis and evidence test.",
            "Expected MFA to block login; observed token reuse. Hypothesis: a pre-policy session token remains valid.",
            "Record expectation, observation, confusion, prerequisite, hypothesis, and test.",
            "Evidence can now resolve the confusion."),
        Step(11, "Perform", "Match the challenge",
            "Match the style, level, and cue of practice to the performance you actually need.",
            "Recognition exercises or generous prompts cannot establish unaided complex performance.",
            "1. Name the target style: explain, query, investigate, build, decide, or present.\n2. Match its cognitive level.\n3. Match its cue: question, partial evidence, discussion, or no cue.\n4. Practise in the same ballpark and inspect the artifact and reasoning.",
            "Investigate mixed endpoint/network evidence, state confidence, choose containment, and write an incident update.",
            "Record style, challenge level, cue type, artifact, decision, confidence, and trade-offs.",
            "Practice matches real style, level, and cue and produces an inspectable output."),
        Step(12, "Perform", "Attempt before feedback",
            "Generate and preserve a complete response before viewing answers, hints, documentation, or AI feedback.",
            "Recognition is not recall; attempting first exposes the real model and primes correction.",
            "1. Time-box and preserve first reasoning.\n2. Consult help only afterward.\n3. Compare reasoning and explain every important miss.",
            "Write and predict a detection query before asking AI to improve it; test both and explain differences.",
            "Record the unaided attempt, help used, differences, and causes of misses.",
            "The original attempt remains visible beside the correction."),
        Step(13, "Retain & Communicate", "Test at the right frequency",
            "Test after enough delay to forget roughly 20–30%, then adapt the interval from the result.",
            "Testing too early adds little effort; testing too late becomes expensive relearning.",
            "1. Predict a first window—often one week to one month.\n2. Retrieve without cues and estimate what was missing.\n3. Lengthen if almost nothing was forgotten.\n4. Shorten after major relearning.\n5. Aim near 20–30% forgetting, not a rigid schedule.",
            "Day 3 rebuild the flow; Day 7 investigate logs; Day 21 brief risk; Day 30 connect a new attack path.",
            "Record interval, unaided result, estimated percentage forgotten, and next-interval decision.",
            "The next review follows observed forgetting rather than a fixed streak."),
        Step(14, "Retain & Communicate", "Match the conditions that matter",
            "Rehearse meaningful pressures—especially intensity, nervousness, scrutiny, and time.",
            "Matching every environmental detail is impractical; matching performance pressures is useful.",
            "1. List meaningful constraints: time, scrutiny, uncertainty, interruptions, and cues.\n2. Choose the two or three that most alter performance.\n3. Rehearse with realistic timing and information limits.\n4. Add questioning when the task requires defence.\n5. Debrief judgement under pressure, not room similarity.",
            "In 30 minutes, triage partial telemetry, state unknowns, recommend containment, and brief SOC lead and executive.",
            "Record conditions, evidence, uncertainty, three briefings, recommendation, and decision request.",
            "You perform and communicate accurately under target-role conditions."),
    ];

    private static LearningStepGuide Step(int number, string phase, string title, string what,
        string why, string how, string example, string prompt, string done) =>
        new(number, phase, title, what, why, how, example, prompt, done);
}
