namespace CyberLearningOS.Windows;

public sealed record StepLesson(
    string Technique,
    string Explanation,
    string Avoid,
    IReadOnlyList<string> Diagram,
    string GuidedPractice,
    string TranscriptAnchor);

public static class TeachingContent
{
    public static readonly IReadOnlyList<StepLesson> Lessons =
    [
        L("Outcome scoreboard", "Judge a method by usable depth, delayed retention, and transfer. Fast coverage can create fragile familiarity and expensive relearning.", "Do not keep or reject a method merely because today's session felt fast or slow.", ["METHOD", "DEEP USE", "DELAY", "TRANSFER", "OUTCOME"], "Close the source, reconstruct an authentication flow, diagnose a broken login, then repeat later with a different case.", "Video 1:04–2:24 — replace speed with depth and retention."),
        L("Purpose-and-plan canvas", "The brain needs a goal and context. Formal study provides objectives; professional learning requires you to create them.", "Do not begin with a vague instruction such as ‘learn cloud security’.", ["PURPOSE", "OBJECTIVES", "PERFORMANCE", "EVIDENCE"], "Define why token abuse matters, four questions you must answer, and the incident task that will prove learning.", "Video 2:27–3:37 — create a clear purpose and plan first."),
        L("Time-block design", "Available time changes which strategy is realistic. Long blocks support integration; short blocks suit priming or retrieval.", "Do not rely on spare time or force a long-session method into a ten-minute gap.", ["CALENDAR", "PRIME", "LEARN", "PERFORM", "REVIEW"], "Use ten minutes to preview SIEM concepts, sixty to connect logs, and thirty later for an unaided hunt.", "Video 3:38–4:17 — schedule first because time changes method choice."),
        L("Priming preview", "A light preview tells the brain what is coming, creates landmarks, and reduces overwhelm during intensive learning.", "Do not turn priming into full study.", ["PREVIEW", "LANDMARKS", "QUESTIONS", "INTENSIVE STUDY"], "Preview a malware lab's process tree, persistence points, tools, and expected report without investigating the sample.", "Video 4:18–5:27 — place a smaller priming block before learning."),
        L("Gist map", "Priming should create a rough whole so later details have meaningful attachment points.", "If priming an hour of material takes much longer than five to ten minutes, you are probably studying details.", ["WHO/WHAT", "FLOW", "BOUNDARY", "EVIDENCE", "PURPOSE"], "Write one plain-language EDR gist, draw five anchor nodes, mark uncertain links, and stop at ten minutes.", "Video 5:28–6:55 — prime for gist, not details."),
        L("Distraction sheet", "A focus environment is measured with a blank sheet that records every attention break and exposes repeated causes.", "Do not decide the environment is focused from intuition or chase each tangent.", ["FOCUS", "DISTRACTION", "TALLY", "REMOVE CAUSE", "RETRY"], "During PCAP work, tally chat, unrelated searches, and DNS uncertainty; contain each trigger before the next block.", "Video 7:14–7:51 — use a distraction sheet; ideally it remains blank."),
        L("Schema-building questions", "Comparing, judging importance, and connecting ideas creates the schemas stored as memory.", "Do not make memorisation or flashcards the first resort; reserve them for arbitrary residue.", ["NEW IDEA", "COMPARE", "JUDGE", "CONNECT", "SCHEMA"], "Compare EDR and NDR by visibility, blind spots, evidence, evasion, cost, and supported decisions.", "Video 7:53–10:52 — trying to remember is a poor way to remember."),
        L("Relational note map", "Non-linear notes expose your reasoning and relationships. Linear notes are mainly a deliberate reference exception.", "Do not transcribe the source or add decorative arrows without reasoning about the links.", ["QUESTION", "MECHANISM", "ATTACK", "TELEMETRY", "DECISION"], "Map token lifecycle → replay opportunity → evidence → correlation → containment, with labelled ‘fails when’ links.", "Video 10:54–12:24 — use relational notes to see connections."),
        L("Relevance-led route", "Learn in the order your current knowledge can make meaningful. Easier related ideas can supply context for a hard point.", "Do not blindly follow chapter order, force an opaque point, or memorise it to escape difficulty.", ["HARD POINT", "MISSING CONTEXT", "EASIER NODE", "CONNECT", "RETURN"], "Step back from Kerberos delegation to tickets, principals, and trust boundaries, then return to the attack path.", "Video 12:25–13:45 — individualise order by relevance."),
        L("Confusion compass", "Confusion reveals a gap found through comparison. Convert the feeling into a focused question and evidence test.", "Do not oversimplify, under-question, or treat the absence of confusion as mastery.", ["CONFUSION", "CONFLICT", "QUESTION", "HYPOTHESIS", "EVIDENCE"], "Turn ‘MFA succeeded but travel is impossible’ into a question about new authentication versus session-token reuse.", "Video 15:25–19:15 — explore confusion rather than escape it."),
        L("Challenge matcher", "Practice must match real performance across style, cognitive level, and cue.", "Do not use definitions or multiple choice to validate an investigation, decision, discussion, or presentation.", ["STYLE", "LEVEL", "CUE", "SIMULATION", "PERFORMANCE"], "Investigate unfamiliar logs without a query hint, explain alternatives, decide, and brief—rather than define beaconing.", "Video 19:16–21:01 — match challenge style, level, and cue."),
        L("Attempt-feedback boundary", "Generating a response before feedback exercises recall and primes correction. Looking first only tests recognition.", "Do not reveal answers before trying, overwrite the first attempt, or let AI silently supply the reasoning.", ["CLOSED BOOK", "GENERATE", "FREEZE", "FEEDBACK", "CORRECT"], "Write and predict a Sigma rule before opening a reference or AI critique; preserve and compare both versions.", "Video 21:02–23:22 — generate a full response before feedback."),
        L("Forgetting calibration", "Test after enough forgetting to make retrieval effortful but before relearning dominates—roughly twenty to thirty percent forgotten.", "Do not use a rigid universal schedule, test immediately, or wait for total collapse.", ["LEARN", "FORGET SOME", "RETRIEVE", "CALIBRATE", "NEXT INTERVAL"], "Rebuild an incident decision tree after two weeks and widen or shorten the next interval from what actually survived.", "Video 23:23–24:58 — calibrate near 20–30% forgetting."),
        L("Pressure rehearsal", "Match conditions that materially change performance: intensity, nervousness, scrutiny, time, and meaningful information limits.", "Do not copy room, food, or caffeine while ignoring timing, ambiguity, and questioning.", ["REAL TASK", "TIME", "SCRUTINY", "UNCERTAINTY", "REHEARSE"], "Triage partial telemetry in thirty minutes, then defend confidence and containment when challenged with conflicting evidence.", "Video 24:59–26:37 — reproduce meaningful pressure, not every environmental detail."),
    ];

    public static StepLesson ForStep(int number) => Lessons[Math.Clamp(number - 1, 0, Lessons.Count - 1)];

    private static StepLesson L(string technique, string explanation, string avoid,
        IReadOnlyList<string> diagram, string practice, string anchor) =>
        new(technique, explanation, avoid, diagram, practice, anchor);
}
